all:
	cd binary-trees; make measureNew

	cd fannkuch-redux; make measureNew

	cd fasta; make measureNew

	cd n-body; make measureNew
	
	cd regex-redux; make measureNew

	cd reverse-complement; make measureNew

	cd spectral-norm; make measureNew
